### ISSUE TITLE
Rotary Position Embedding

### ISSUE THREAD

**Issue by entron** [s-chh/PyTorch-Scratch-Vision-Transformer-ViT#2]
I really enjoy reading your code; it is very clear and easy to understand, while also achieving top results in the benchmarks! I would like to explore [Rotary Position Embedding ](https://medium.com/@ngiengkianyew/understanding-rotary-positional-encoding-40635a4d078e)(used by LLAMA models) using your example. Have you already tried it? Do you have any exprience with it used in ViT?

**Comment by s-chh** [comment]
Thank you for the comments. I don't have experience with Rotary Position Embedding. At a glance, it looked like it was for 1D sequential data like text. I will see if it has been adopted for images and get back in a few days.

**Comment by s-chh** [comment]
Rotational Embedding is for 1-D sequences. I am still figuring out how to make it work for 2-D data, but it might not be so straightforward. Any suggestions would help.

**Comment by entron** [comment]
I have contacted the Jianlin Su who is the original author of Rotational Embedding. He pointed me this link: [Transformer升级之路：4、二维位置的旋转式位置编码](https://kexue.fm/archives/8397)[Transformer升级之路：4、二维位置的旋转式位置编码](https://kexue.fm/archives/8397)

**Comment by s-chh** [comment]
I have created a new repository with different types of positional embeddings for Vision Transformers. Would appreciate your feedback on it.

Here is the link: https://github.com/s-chh/Vision-Transformer-ViT-Positional-Embeddings

**Comment by s-chh** [comment]
Feel free to open it here or raise an issue on the new repo if you need anything.

**Comment by entron** [comment]
Very nice work! I will try to play with it when I got some spare time.
