### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by liork9** [s-chh/PyTorch-Scratch-Vision-Transformer-ViT#5]
Thank you for publishing this code !!
I want to run it and cite it in an academic paper.
Can you please add a license? Preferably MIT license if possible.

link to the procedure:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks

**Comment by s-chh** [comment]
Thank you for using and citing my work. I have added the MIT license to the repository.

**Comment by liork9** [comment]
Thanks
